spring.application.name=FourParks
app.base-url=${APP_BASE_URL:http://localhost:3000}

# Database configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/fourparks}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.postgresql.Driver}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=false
logging.level.org.hibernate.orm.jdbc.bind=WARN


# Security configuration
security.jwt.key.private=${JWT_PRIVATE_KEY}
security.jwt.user.generator=AUTH-USER

# Email configuration
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true